version: "3.8"
services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8084:8084"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: "mongodb://mongo:27019"
      REDIS_URI: "redis://redis:6379"

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
